### ISSUE TITLE
Gurobi for optimization?

### ISSUE THREAD

**Issue by eiiijiiiy** [VasileiosBouzas/MeshSimplification#10]
Hello dear authors!

Is there a version of MeshPolygonization that can do its optimization through Gurobi like the baseline PolyFit? 

Best,
Yijie

**Comment by LiangliangNan** [comment]
Thanks for the question.
Mesh Polygonization is an order of magnitude faster than its baseline, and that is why the Gurobi was not included. 
If you did encounter a computation bottleneck, I can add the Gurobi. I may have some time in mid-Sept.

**Comment by eiiijiiiy** [comment]
Actually, we would like to compare our method, PolyFit, and Mesh Polygonization all with Gurobi to have a relatively fair comparison. It would be very convenient for us if Gurobi can be added.

Thank you very much for your kind support!!

**Comment by LiangliangNan** [comment]
Maybe you can use the SCIP solver (that is already included in both PolyFit and Mesh Polygonization). Or is there a particular reason to use Gurobi?

**Comment by LiangliangNan** [comment]
Now Gurobi is included. 
For comparison, you can choose either SCIP or Gurobi.

**Comment by eiiijiiiy** [comment]
Thank you very much for such generous support!! 
It seems too slow to use SCIP for our cases. There could be tens or more RANSAC plane segments there for the solvers.
We will test it with this gurobi implementation and probably have a chance to discuss later。
