### ISSUE TITLE
CGAL::Assertion_exception

### ISSUE THREAD

**Issue by eiiijiiiy** [VasileiosBouzas/MeshSimplification#11]
Dear authors,

Sorry to bother you again!

We ran the Mesh Polygonization on our [data](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/yijiewu_connect_hku_hk/Ed2VYn-WgPRLmHqVzh3oG6IB3WKaFMG8bjrCKDctWDalpw?e=4FczOA).

But CGAL (ver: 5.4.1) threw an error. 
The log is pasted below.

>  Parameters (You may need to modify some of them) -------
	Distance threshold: 0.8
	Importance threshold: 0
	Solver: Gurobi 
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: _idx < data_.size()
File: /usr/local/include/CGAL/Surface_mesh/Properties.h
Line: 193
Aborted (core dumped)

It seems that our data doesn't fit some requirements of the planarity calculation.
May you kindly suggest some tips to prepare the test data?

Many thanks!!

**Comment by LiangliangNan** [comment]
I quickly looked into your data and found that it has non-manifoldness (to be specific: isolated vertices).
I updated the code so now it can handle such defect inputs.
Besides, you may also need to tune the parameters to generate a reasonably good result. I tried and you can start by setting the `dist_threshold = 1.5`. I highly suggest reading our paper to get an idea what the parameters mean.

**Comment by LiangliangNan** [comment]
I believe this issue has been resolved so I am going to close it. If this is not the case, feel free to reopen it.

**Comment by eiiijiiiy** [comment]
Sorry for my late reply.
Yeah, perfectly solved it. 
Thanks very much!!
