### ISSUE TITLE
how to built

### ISSUE THREAD

**Issue by Magical1-zyz** [VasileiosBouzas/MeshSimplification#13]
I am a newbie in computer graphic,
I have made this project with cmake,
and what should I do next?
I have create build folder and built it with cmake,
but I don't know how to use it

**Comment by LiangliangNan** [comment]
The build process is almost standard. Please refer to the build section of my other project:
https://github.com/LiangliangNan/Easy3D#build-easy3d

**Comment by Magical1-zyz** [comment]
thanks，I will see it later
