### ISSUE TITLE
The MeshPolygonization's code is short of "Draw.h" header file

### ISSUE THREAD

**Issue by Nike-H1** [VasileiosBouzas/MeshSimplification#3]
Hello, Vasileios!
Thanks for the open source code and your great work. I'm trying to use your code to do some experiment. But during the experiment, I found that the ‘’Draw.h‘’ header file is missing in the MeshPolygonization folder.

Kind regards,
Bing

**Comment by LiangliangNan** [comment]
@lhbing-alt The "Draw.h" was actually not used so it can be simply commented out. 
Please grab and use the updated code.

**Comment by LiangliangNan** [comment]
I assume the issue has been resolved so I will close it.
