### ISSUE TITLE
Can't download the full code

### ISSUE THREAD

**Issue by sahar-github** [VasileiosBouzas/MeshSimplification#4]
I can not download the full code

**Comment by LiangliangNan** [comment]
Which file is missing?

**Comment by sahar-github** [comment]
Hi
Thanks for the reply, i just wanted to inform about a bug on the website,
if I press the code button, I can not get the full zip file.
I will try to download each file seperately and would like to test it on my
own dataset.
Thank you for your time and consideration
Best
Sahar

**Comment by sahar-github** [comment]
I just actually want to see if its possible to download the zip file of the code and try to test it?

**Comment by LiangliangNan** [comment]
Tested just now and worked without any problem.
This *website* is owned by Microsoft. Do you have the same issue when downloading the source code from other repositories?

**Comment by sahar-github** [comment]
No i do not have any problem downloading from other links. thatswhy I thought its better i inform about it

**Comment by sahar-github** [comment]
but i really like your research, it is very interesting, and I am counting the seconds until I can run it on my own data to see how it really works
