### ISSUE TITLE
Failed to open file '../../../data/building.off'.

### ISSUE THREAD

**Issue by sahar-github** [VasileiosBouzas/MeshSimplification#5]
When i run the executable I see the following error. is there something missing in the data? or what should i do? 
how can i prepare my own dataset to be processed?
Thanks in advance for your response

**Comment by LiangliangNan** [comment]
"Failed to open file '../../../data/building.off'" 
this really depends on where you generate your "build" directory. You can simply modify the file path to the directory where the data is.

**Comment by LiangliangNan** [comment]
This is quite trivial, so I am closing this issue.
Feel free to open it again if necessary.

**Comment by sahar-github** [comment]
Thank you very much for the response and declaration
Best
Sahar
