### ISSUE TITLE
Failed loading model from the file.

### ISSUE THREAD

**Issue by sahar-github** [VasileiosBouzas/MeshSimplification#7]
What kind of problem the input mesh might have? when I get this error message?
I see in the code is written if (!(input >> mesh)), 

Thanks in advance for your response!
Best 
Sahar

**Comment by LiangliangNan** [comment]
might be:
 - your file doesn't appear in the correct path (e.g., relative path vs absolute path);
 - not recognized file format. I think the current implementation only supports off format (but not quite sure).
 - the file contains errors so the reader failed parsing your file.

You can look at how the  ">>" operator was implemented and use debug mode to understand the actual reason.
You can also reimplement the ">>" to allow more types of formats or replace it with your loading function.

**Comment by sahar-github** [comment]
Hii
Thanks for your response. I first made a surface reconstruction using
Reality capture and used the resulting output mesh as an input for your
routine. It seems this output was not a good input for the model, and thats
why I got this error message.
Afterwards, I tried to bring the output mesh of the reality capture for
another data in the meshlab and made a poisson surface remeshing, it seems
that helped to make the file ready for processing in your routine.
I started running the code with the above mentioned final input on Monday
evening and since then, still the code is running. I see the number of
estimated planes are 27235.
Do you think is this normal to wait this long? do you have any suggestions/
comments which help me to run it faster?
Thanks & Regards
Sahar

**Comment by sahar-github** [comment]
Here is the link to my current/new input data, 
https://wetransfer.com/downloads/5e1c5a1d86dda60254361ae1e571e60f20210311105134/a0a4b3edaf99bf3adfb89ce94bee86ae20210311105156/e2f73d 

In general, I think it will be a really good help if there be a guideline available for a good/suitable preparation of own dataset, in order to make it compatible with the method.
I would appreciatie any guideline in that regard
Best 
Sahar

**Comment by LiangliangNan** [comment]
If read our paper you will understand the limitation of the method (i.e., no fast solver available that can solve our optimization problem given a large number of planes).

You can start with a simpler model, and try to tune the parameters to increase the number of planes and see and fee how it affects the performance.
Alternatively, you can look at our provided models to get an idea of how complex our inputs are.

**Comment by sahar-github** [comment]
Hi Nan
Thanks for the information, I actually studied the complete thesis and the paper, which was definitely very informative. I also tried to test on some simple models (only a building which looks like a cube) 
I am still changing different parameters and I get like several individual small polygons, or nothing, or very small polygon each time of run. 

I was wondering, is there any other suggestion than try-and-error on the parameter tuning in case  of using own data? 

I feel there has to be some specific settings also for the creation of the input mesh, which will influence alot on the resulting output (at least this is the case for me)
Thank you in advance for your consideration and time
Best regards
Sahar

**Comment by sahar-github** [comment]
I am also just wondering in case we want to make the model more automatice, can we think of any relationship to the data resolution or similar measures to make the parameter tunning easier probably? 
Here I am kind of brain storming :)

**Comment by LiangliangNan** [comment]
In general, to make it work, you will need to choose parameters for the plane extraction step such that 
 - all necessary planes capturing the desired geometric features can be obtained.
 
This is, however, usually not obvious due to different levels of complexity, noise, outliers, and missing data. Thus I don't know if this can be made (semi)automatic. Maybe involving some user interaction could do, but that is another story then.
In practice, I would suggest starting from a coarse model and then tuning the parameters to add more (but limited) details.
