### ISSUE TITLE
The experimental data provided in the application code cannot achieve the experimental results in the paper

### ISSUE THREAD

**Issue by Nike-H1** [VasileiosBouzas/MeshSimplification#9]
Excuse me, the experimental data provided in the code cannot achieve the experimental results in the paper

**Comment by Nike-H1** [comment]
I adjusted the parameters many times, but all failed

**Comment by LiangliangNan** [comment]
No actual information is provided :-(
When reporting an issue, please let us know
 - which data?
 - what parameters?
 - what the error messages are, or explain what has been observed.
 - which version of CGAL is used?
 - which operating system?
The authors need to know how to reproduce the issue before they can explore it.

BTW, here are the parameters used for the example data:
https://github.com/VasileiosBouzas/MeshPolygonization/tree/master/data

**Comment by Nike-H1** [comment]
The parameters of distance and importance are different for each data, so how to get the optimal parameters. In addition, the objective function consists of three energy terms: face coverage, data fitting, and model complexity. How to adjust these three parameters？

**Comment by LiangliangNan** [comment]
For this issue, you reported that the program failed to reproduce the expected result. Have you tested the given parameters? How do the results look like?

> The parameters of distance and importance are different for each data, so how to get the optimal parameters. In addition, the objective function consists of three energy terms: face coverage, data fitting, and model complexity. How to adjust these three parameters？

This is a research prototype and it may require tuning the parameters. 
The best set of parameters always depends on the complexity of the object and the quality of the point cloud.
For many models we have tested, the same set of parameters work well. I suggest you start with the default parameters and tune them when necessary. 
Please have a look at ["About the parameters"](https://github.com/VasileiosBouzas/MeshPolygonization#about-the-parameters). It would also be very helpful to read our paper to understand how these  
parameters affect the result.
